CREATE CONSTRAINT account_id IF NOT EXISTS
FOR (a:Account)
REQUIRE a.id IS UNIQUE;

CREATE CONSTRAINT person_id IF NOT EXISTS
FOR (p:Person)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT bank_id IF NOT EXISTS
FOR (b:Bank)
REQUIRE b.id IS UNIQUE;